### ISSUE TITLE
Cloud Storage support

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/pste#4]
Is it possible to support cloud storage backends for app data? I am using Google Drive mounted over rclone using crypt and have it mounted system wide for use in uPste but there's a larger delay in retrieving files vs locally as well as files failing the first time over ShareX due to the file not appearing in the mount yet.

Would it be possible to support B2 or Google Drive as a remote storage option?

**Comment by camjac251** [comment]
Rclone is really nice to use for encrypting storage on cloud servers so this wrapper for python might be useful https://pypi.org/project/python-rclone/

**Comment by lwatsondev** [comment]
I have no intention of adding cloud storage as it's a lot of work for something I will never use. I would suggest you look into [mounting your drive account as a FUSE filesystem](https://github.com/astrada/google-drive-ocamlfuse) instead.
