### ISSUE TITLE
File Viewer page

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/pste#5]
If it's too much for this simple project it's ok but I was wondering if maybe it would be possible to have a file viewer built into the project.

Like going to pste.pw/GeD.avi would allow for a direct download, but going to pste.pw/GeD might lead to a page with file info on the right (creation date, any saved metadata, resolution, colorspace) and a player/image viewer on the left with possible transcoding to play files in an external web library.

Files are forced to download because browsers don't support WAV,TIFF, some mp4's with no +faststart added to the encoding,

**Comment by lwatsondev** [comment]
[Text is already viewable as a paste with file info, syntax highlighting etc at `/p/<slug>` (as opposed to `/f/<slug>` for the plaintext version).](https://dev.pste.pw/p/2JD) I'm not doing an online media player as it's well outside the scope of pste. It's a file sharing app, not a youtube clone. ;)

**Comment by camjac251** [comment]
That's understandable. I didn't know about the syntax highlighter so that'll be cool. Is it ready for testing?
